<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="OpenIddict.Client.SystemIntegration" />
    <PackageReference Include="OpenIddict.Client.SystemNetHttp" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <ProjectReference Include="..\Asterloom.Sdk\Asterloom.Sdk.csproj" />
    <ProjectReference Include="..\Asterloom.Shared\Asterloom.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
