<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Asterloom.Module.Authorization\Asterloom.Module.Authorization.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Feature\Asterloom.Module.Feature.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Config\Asterloom.Module.Config.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Release\Asterloom.Module.Release.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module\Asterloom.Module.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Identity\Asterloom.Module.Identity.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Infrastructure\Asterloom.Module.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Targeting\Asterloom.Module.Targeting.csproj" />
    <ProjectReference Include="..\..\Asterloom.Sdk.Identity.AspNetCore\Asterloom.Sdk.Identity.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Asterloom.Server\Asterloom.Server.csproj" />
  </ItemGroup>

</Project>
