<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
    <IncludeGoogleApiCommonProtos>true</IncludeGoogleApiCommonProtos>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos/reference_app.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
