<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="AWSSDK.S3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Asterloom.Module.Analytics\Asterloom.Module.Analytics.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Authorization\Asterloom.Module.Authorization.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Config\Asterloom.Module.Config.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Feature\Asterloom.Module.Feature.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Mail\Asterloom.Module.Mail.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Release\Asterloom.Module.Release.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Targeting\Asterloom.Module.Targeting.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Storage\Asterloom.Module.Storage.csproj" />
    <ProjectReference Include="..\Asterloom.Module.Telemetry\Asterloom.Module.Telemetry.csproj" />
    <ProjectReference Include="..\Asterloom.Module\Asterloom.Module.csproj" />
    <ProjectReference Include="..\Asterloom.Shared\Asterloom.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
