<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Asterloom.Module.Analytics\Asterloom.Module.Analytics.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Authorization\Asterloom.Module.Authorization.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Config\Asterloom.Module.Config.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Feature\Asterloom.Module.Feature.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module\Asterloom.Module.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Identity\Asterloom.Module.Identity.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Infrastructure\Asterloom.Module.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Release\Asterloom.Module.Release.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Storage\Asterloom.Module.Storage.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Targeting\Asterloom.Module.Targeting.csproj" />
    <ProjectReference Include="..\..\Asterloom.Module.Telemetry\Asterloom.Module.Telemetry.csproj" />
  </ItemGroup>

</Project>
